version: '3'
services:
  dynamodb:
    image: tray/dynamodb-local
    ports:
      - "7777:7777"
    command: "-inMemory -port 7777"
  esearch:
    image: "opensearchproject/opensearch:2.5.0"
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
  minio1:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: "FAKE_ACCESS_KEY"
      MINIO_SECRET_KEY: "FAKE_SECRET_ACCESS_KEY"
    command: "server /data"
